// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGC46MmI_xBciWzdRKW-LGs-WizgyMdJA',
    appId: '1:304831392698:web:cf84d4efa77c4678298b83',
    messagingSenderId: '304831392698',
    projectId: 'damtrade-c6055',
    authDomain: 'damtrade-c6055.firebaseapp.com',
    storageBucket: 'damtrade-c6055.appspot.com',
    measurementId: 'G-3ZXSQT067V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBVATvgWhUyIf3_6nj8lhqggf3aGQeiHU',
    appId: '1:304831392698:android:f99122aa20b4fcf6298b83',
    messagingSenderId: '304831392698',
    projectId: 'damtrade-c6055',
    storageBucket: 'damtrade-c6055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj04TxE9s8hU0X6hjwgzyh4VfGKvXQZOE',
    appId: '1:304831392698:ios:5b164bedf1bc49f3298b83',
    messagingSenderId: '304831392698',
    projectId: 'damtrade-c6055',
    storageBucket: 'damtrade-c6055.appspot.com',
    iosClientId: '304831392698-lt64sh735t64vmnpvmre3n46tgcd9k18.apps.googleusercontent.com',
    iosBundleId: 'com.example.damtrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj04TxE9s8hU0X6hjwgzyh4VfGKvXQZOE',
    appId: '1:304831392698:ios:5b164bedf1bc49f3298b83',
    messagingSenderId: '304831392698',
    projectId: 'damtrade-c6055',
    storageBucket: 'damtrade-c6055.appspot.com',
    iosClientId: '304831392698-lt64sh735t64vmnpvmre3n46tgcd9k18.apps.googleusercontent.com',
    iosBundleId: 'com.example.damtrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGC46MmI_xBciWzdRKW-LGs-WizgyMdJA',
    appId: '1:304831392698:web:4e066402922db66c298b83',
    messagingSenderId: '304831392698',
    projectId: 'damtrade-c6055',
    authDomain: 'damtrade-c6055.firebaseapp.com',
    storageBucket: 'damtrade-c6055.appspot.com',
    measurementId: 'G-LY2579PTTL',
  );
}
